run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional recommended linters
    - bodyclose
    - dogsled
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - stylecheck
    - unconvert
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment # Too noisy

  gocyclo:
    min-complexity: 30

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - ifElseChain
      - commentedOutCode

  gosec:
    excludes:
      - G104 # Audit errors not checked (too noisy for deferred closes)
      - G304 # Potential file inclusion via variable (expected behavior)
      - G306 # Poor file permissions used when writing file (we use restrictive perms)

  stylecheck:
    checks:
      - all
      - -ST1000 # Package comments not required
      - -ST1003 # Underscore in package name OK for test packages

  dupl:
    threshold: 150

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocyclo
        - errcheck

    # Allow init functions in CLI package for cobra command setup
    - path: internal/cli/
      linters:
        - gochecknoinits

    # Allow longer functions in build package (complex logic)
    - path: internal/build/
      linters:
        - gocyclo

    # Exclude test helpers from most checks
    - path: test/
      linters:
        - dupl
        - gosec
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 10
